# my-systemverilog-examples pipeline.yml

jobs:

- name: job-readme-github-pages
  plan:
  - get: my-systemverilog-examples
    trigger: true
  - put: resource-slack-alert
    params:
      channel: '#jeff-builds'
      text: "From my-systemverilog-examples: STARTED job-readme-github-pages in concourse ci."
  - put: resource-repo-status
    params: { state: "pending", description: "STARTED job-readme-github-pages in concourse ci.", commit: "my-systemverilog-examples" }
  - task: task-readme-github-pages
    file: my-systemverilog-examples/ci/tasks/task-readme-github-pages.yml
    on_success:
      do:
      - put: my-systemverilog-examples
        params:
          repository: my-systemverilog-examples-updated  
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From my-systemverilog-examples: PASSED job-readme-github-pages in concourse ci."
      - put: resource-repo-status
        params: { state: "success", description: "PASSED job-readme-github-pages in concourse ci", commit: "my-systemverilog-examples" }
    on_failure:
      do:
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From my-systemverilog-examples: FAILED job-readme-github-pages in concourse ci."
      - put: resource-repo-status
        params: { state: "failure", description: "FAILED job-readme-github-pages in concourse ci", commit: "my-systemverilog-examples" }

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master

resources:

- name: my-systemverilog-examples
  type: git
  source:
    #uri: https://github.com/jeffdecola/my-systemverilog-examples
    uri: git@github.com:jeffdecola/my-systemverilog-examples.git
    branch: master
    private_key: {{git_private_key}}
- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}} 
- name: resource-repo-status 
  type: github-status
  source:
    repository: jeffdecola/my-systemverilog-examples 
    access_token: {{repo_github_token}}
